"""Factor Research design engine public API."""

from .financial import (
    data_freshness,
    delta,
    format_financial,
    metric_value,
    model_verdict,
    score_badge,
)
from .layouts import analysis_grid, container, dashboard_grid, page_header, stack
from .primitives import (
    alert,
    banner,
    button,
    card,
    confirmation_dialog,
    empty_state,
    form_field,
    retry_panel,
    search_control,
    status_region,
    tab,
)
from .schemas import InteractionState, SectionDefinition, SectionRegistry, SectionState, UIState
from .states import (
    background_job_status,
    card_skeleton,
    chart_skeleton,
    inline_pending_indicator,
    partial_data_notice,
    section_error,
    stage_progress,
    stale_data_notice,
    table_skeleton,
)

__all__ = [
    "SectionDefinition",
    "SectionRegistry",
    "SectionState",
    "UIState",
    "InteractionState",
    "alert",
    "analysis_grid",
    "background_job_status",
    "banner",
    "button",
    "card_skeleton",
    "chart_skeleton",
    "card",
    "container",
    "confirmation_dialog",
    "dashboard_grid",
    "data_freshness",
    "delta",
    "empty_state",
    "form_field",
    "format_financial",
    "inline_pending_indicator",
    "metric_value",
    "model_verdict",
    "page_header",
    "partial_data_notice",
    "retry_panel",
    "score_badge",
    "section_error",
    "search_control",
    "stack",
    "stage_progress",
    "stale_data_notice",
    "status_region",
    "table_skeleton",
    "tab",
]
