#!/usr/bin/env python3
"""Reject new design-system bypasses while legacy migration remains incremental."""

import re
import subprocess
import sys
from pathlib import Path

RAW_COLOR = re.compile(r"(?<![\w-])(?:#[0-9a-fA-F]{3,8}\b|rgba?\()")
APPROVED = {
    "codes/app_modules/design_system/tokens.py",
    "assets/style/_design_tokens.generated.scss",
    "assets/style/_tokens.scss",
    "assets/_colors.scss",
}
LEGACY_VALUE_EXCEPTIONS = (
    '"rgba(0,0,0,0)"',
    '"rgba(126, 157, 194, 0.18)"',
    '"rgba(158,158,158,0.12)"',
    '"#001a0a"',
    '"#2a2000"',
    '"#2a0000"',
)
ONE_OFF_CONSTRUCTORS = {
    "html.Button(": "use design_system.primitives.button",
    "dcc.Link(": "use design_system.primitives.link",
    "dcc.Loading(": "use design_system.primitives.loading_container",
    "dcc.Input(": "use design_system.primitives.input_control",
    "dcc.Dropdown(": "use design_system.primitives.select_control",
    "dcc.Slider(": "use design_system.primitives.slider",
    "dcc.Checklist(": "use design_system.primitives.checkbox_group or switch",
    "dcc.RadioItems(": "use design_system.primitives.radio_group",
    "html.Table(": "use design_system.primitives.table or responsive_table",
}


def changed_additions() -> list[tuple[str, str]]:
    result = subprocess.run(
        ["git", "diff", "--unified=0", "--", "*.py", "*.scss"],
        check=True,
        capture_output=True,
        text=True,
    )
    path = ""
    additions = []
    for line in result.stdout.splitlines():
        if line.startswith("+++ b/"):
            path = line[6:]
        elif line.startswith("+") and not line.startswith("+++"):
            additions.append((path, line[1:]))
    return additions


def protected_source_failures() -> list[str]:
    failures = []
    protected_sources = [
        *(
            source
            for source in Path("codes/app_modules/design_system").glob("*.py")
            if source.name != "tokens.py"
        ),
        Path("assets/style/_design_system.scss"),
    ]
    for source in protected_sources:
        for line_number, line in enumerate(source.read_text().splitlines(), 1):
            if RAW_COLOR.search(line):
                failures.append(f"{source}:{line_number}: raw color in protected source")
            if source.suffix == ".scss" and "z-index:" in line and "var(--fr-layer-" not in line:
                failures.append(f"{source}:{line_number}: unmanaged z-index")
            if (
                source.suffix == ".scss"
                and "border-radius:" in line
                and "var(--fr-radius-" not in line
            ):
                failures.append(f"{source}:{line_number}: unmanaged radius")
    return failures


def changed_value_failures() -> list[str]:
    failures = []
    for path, line in changed_additions():
        if path in APPROVED or "design-system-exception:" in line:
            continue
        if RAW_COLOR.search(line) and not any(value in line for value in LEGACY_VALUE_EXCEPTIONS):
            failures.append(f"{path}: raw color bypass")
        if path.endswith(".scss") and "z-index:" in line and "var(--fr-layer-" not in line:
            failures.append(f"{path}: unmanaged z-index")
        if path.endswith(".scss") and "border-radius:" in line and "var(--fr-radius-" not in line:
            failures.append(f"{path}: unmanaged radius")
    return failures


def one_off_constructor_failures() -> list[str]:
    failures = []
    production_sources = Path("codes/app_modules").rglob("*.py")
    for source in production_sources:
        if "design_system" in source.parts:
            continue
        contents = source.read_text()
        for constructor, replacement in ONE_OFF_CONSTRUCTORS.items():
            if constructor in contents:
                failures.append(f"{source}: one-off {constructor[:-1]} constructor; {replacement}")
    return failures


def generated_token_failures() -> list[str]:
    generated = Path("assets/style/_design_tokens.generated.scss")
    if (
        not generated.exists()
        or "Generated by scripts/generate-design-tokens.py" not in generated.read_text()
    ):
        return ["generated design tokens are missing"]
    return []


def main() -> int:
    failures = [
        *protected_source_failures(),
        *changed_value_failures(),
        *one_off_constructor_failures(),
        *generated_token_failures(),
    ]
    if failures:
        print("Design-system enforcement failed:")
        print("\n".join(f"- {item}" for item in sorted(set(failures))))
        return 1
    print("Design-system enforcement passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
