#!/usr/bin/env python3
"""Generate CSS custom properties from the typed design token source."""

from pathlib import Path

from codes.app_modules.design_system.tokens import LIGHT_OVERRIDES, token_map

OUTPUT = Path("assets/style/_design_tokens.generated.scss")


def render() -> str:
    dark = "\n".join(f"  --fr-{name}: {value};" for name, value in sorted(token_map().items()))
    light = "\n".join(f"  --fr-{name}: {value};" for name, value in sorted(LIGHT_OVERRIDES.items()))
    return (
        "// Generated by scripts/generate-design-tokens.py. Do not edit.\n"
        f":root, [data-theme='dark'] {{\n{dark}\n}}\n\n"
        f"html.light, body.light, [data-theme='light'] {{\n{light}\n}}\n"
    )


if __name__ == "__main__":
    OUTPUT.write_text(render(), encoding="utf-8")
